client:
  serverUrl: http://localhost:8080/ticket/
  numberOfThreads: 4
  numberOfIterations: 1000
  commonClientId: common
  statistics:
    active: true
    validate: true
    ticketIdFormat: "ticket-%d"
